### ISSUE TITLE
Filters inaccessible in mobile view

### ISSUE THREAD

**Issue by mcrawford** [youssefm/limited-grades#10]
When in mobile view, there is no way to access the Rarity filter and the Type filter.

**Comment by youssefm** [comment]
Appreciate the feedback.

I've reintroduced the filters for mobile:
![image](https://user-images.githubusercontent.com/1513212/159078659-8b484eac-5fbe-40f4-92e4-ed9da22ac857.png)

https://github.com/youssefm/limited-grades/commit/396b522154a86a37d7c6df10b711e91fc2d5b768

**Comment by mcrawford** [comment]
Awesome, thank you. I use the site always in mobile view, and like to eliminate the rares and mythics after the first pick, so this is very helpful.

**Comment by youssefm** [comment]
@mcrawford since you use the site primarily on mobile, can I ask you for your opinion on something?

Would a mobile view that looks something like this:

![image](https://user-images.githubusercontent.com/1513212/159098782-f8d13f0f-aa38-43c6-8aa5-3214e65ec806.png)

be better or worse for you?

**Comment by mcrawford** [comment]
That looks great, I think that would be better. It eliminates the horizontal scrolling, which would be nice. 

I guess the downside would be that it would be more difficult to scan for a card in a certain color. Overall though I think it would be an improvement.

**Comment by youssefm** [comment]
Great, well it's live now :)

I'm looking to implement a separate search feature to make it easier to look for specific cards. Should hopefully help with that problem
