### ISSUE TITLE
Pre 17L data SNC

### ISSUE THREAD

**Issue by Benthem** [youssefm/limited-grades#12]
I've taken the liberty to parse the aggregated data from a reddit post into a SNC json for my local copy of limitedgrades. Maybe you want to use it, maybe you don't.

[snc.zip](https://github.com/youssefm/limited-grades/files/8583247/snc.zip)

(or pastebin at https://pastebin.com/DpXPjyQH )

https://old.reddit.com/r/MagicArena/comments/udry9t/someone_compiled_snc_limited_ratings_but_didnt/

**Comment by youssefm** [comment]
Hey there, thanks for compiling that data. I could see this site eventually incorporating community grades, but I'm not sure how to implement a Web UI that displays them elegantly.

Let me think about this some more. It would be pretty cool to get grades based on 17Lands alongside community grades as well.
