### ISSUE TITLE
HBG and future sets

### ISSUE THREAD

**Issue by jamiesontetc** [youssefm/limited-grades#15]
Think your tool is really a great product. Are you planned to add Horizons Baldur’s Gate and other upcoming sets?

**Comment by youssefm** [comment]
Thanks! I'm definitely planning on adding upcoming sets but I just didn't know about this one.

I've added a page for this set:

https://www.limitedgrades.com/hbg

Let me know if it looks alright.

**Comment by jamiesontetc** [comment]
Looks great, thanks!!!
