### ISSUE TITLE
Separate filters for each artifacts, enchantments, battles, and planeswalkers

### ISSUE THREAD

**Issue by makus82** [youssefm/limited-grades#20]
Great project thx for your work!
Separate filters for each artifacts, enchantments, battles, and planeswalkers 
would be really usefull! pls add them if possible!!!

**Comment by youssefm** [comment]
Hey @makus82, thanks! Can I learn a bit more about why you want different filters for each of those?

On desktop, it wouldn't be very hard to have separate filters, but on mobile, it's really hard to find the space for more than 4 filters:

![image](https://github.com/youssefm/limited-grades/assets/1513212/5773dbd1-da9b-4ec2-ba25-38905e3ae9a4)

Maybe this would be a desktop-only feature, and we'd still group them on mobile? What do you think?

**Comment by makus82** [comment]
well i dont use mobile for such things... so you can just hide extra..
its need for new set drafters to easy find removals, evesions and sinergis... thx [Youssef](https://github.com/youssefm) =]

**Comment by youssefm** [comment]
Don't think I have any interest in addressing myself this. If someone wants to put up a PR to address this in an elegant way that works for mobile, I'm happy to look at it.
