### ISSUE TITLE
API to create an overlay for Arena

### ISSUE THREAD

**Issue by ConsolasTrovao** [youssefm/limited-grades#31]
Hey guys.

Can I take a stab at the code and create an api so that we can have an overlay during drafts with the score of the cards, much like you have on the site?

Would that be something you would accept - the api part? 

That would be needed for the client running in the desktop to get the info.

**Comment by youssefm** [comment]
Hey @ConsolasTrovao, turns out there's already an API, try this link out for example:

https://www.limitedgrades.com/api/cards/lci

**Comment by ConsolasTrovao** [comment]
Hello @youssefm 

Thank you so much for the fast reply! That is awesome! 

Is there any documentation I can check? For instance, is it possible to search for a specific card or group of cards? 

I'm just thinking about the draft where you have multiple cards to select from and I would love to have all scores for every single one of them

Thanks!

**Comment by youssefm** [comment]
There's no documentation, but check out the JSON - it should be pretty easy for you to look up a specific card from the payload

**Comment by ConsolasTrovao** [comment]
Thanks! I will check it and start delving into creating an overlay to use that info in drafts - that is the part I will have to learn so it should be fun! :) 

Thanks!

**Comment by youssefm** [comment]
Good luck! If you end up having any questions about the API, let me know and I can help clear things up.
